### ISSUE TITLE
Disable /etc/cron.weekly/fstrim

### ISSUE THREAD

**Issue by chorrell** [joyent/ubuntu-lx-brand-image-builder#13]
This doesn't make much sense in an lx-brand image.

**Comment by cmosetick** [comment]
As noted on the smartos-dicsuss [mailing list](https://www.listbox.com/member/archive/184463/2016/02/sort/time_rev/page/1/entry/10:163/20160229152214:1C5A0C76-DF22-11E5-B07F-DFEBEF10038B/)
