### ISSUE TITLE
Nice to have add-apt-repository out of the box

### ISSUE THREAD

**Issue by papertigers** [joyent/ubuntu-lx-brand-image-builder#2]
As of right now software-properties-common and python-software-properties are not included with the base image.

This means add-apt-repository is not present on the host.  A lot of guides and documentation tell you to use the tool to add a repository to your host.  Example:

add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer

**Comment by chorrell** [comment]
might need to use the —no-install-recommends flag when installing via apt-get

**Comment by chorrell** [comment]
This should be resolved in 18cc5165b1c11b544091201b1e2d9fdd461164cf
